// <auto-generated />
using System;
using InvestIt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestIt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260125193552_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestIt.Data.Entities.ApiRateLimitTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRefreshTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NetworkId")
                        .HasColumnType("int");

                    b.Property<int>("TokensAvailable")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId")
                        .IsUnique();

                    b.ToTable("ApiRateLimitTrackings");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.BlockchainNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ChainId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RateLimitPerSecond")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChainId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BlockchainNetworks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiUrl = "https://api.etherscan.io/api",
                            ChainId = "1",
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ethereum",
                            RateLimitPerSecond = 5
                        },
                        new
                        {
                            Id = 2,
                            ApiUrl = "https://api.bscscan.com/api",
                            ChainId = "56",
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Binance Smart Chain",
                            RateLimitPerSecond = 5
                        },
                        new
                        {
                            Id = 3,
                            ApiUrl = "https://api.polygonscan.com/api",
                            ChainId = "137",
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Polygon",
                            RateLimitPerSecond = 5
                        },
                        new
                        {
                            Id = 4,
                            ApiUrl = "https://api.solscan.io",
                            ChainId = "solana-mainnet",
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Solana",
                            RateLimitPerSecond = 3
                        });
                });

            modelBuilder.Entity("InvestIt.Data.Entities.MonitoredWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("BlockchainNetworkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlockchainNetworkId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Address", "BlockchainNetworkId")
                        .IsUnique();

                    b.ToTable("MonitoredWallets");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.MonitoringStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("bit");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastErrorTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPollTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NetworkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsHealthy");

                    b.HasIndex("NetworkId")
                        .IsUnique();

                    b.ToTable("MonitoringStatuses");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.NotificationQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("NotificationQueues");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<int>("BlockNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("GasPrice")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<decimal?>("GasUsed")
                        .HasPrecision(38, 18)
                        .HasColumnType("decimal(38,18)");

                    b.Property<string>("RawData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TokenAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TokenSymbol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("TokenSymbol");

                    b.HasIndex("TxHash")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("WalletId", "Timestamp");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.ApiRateLimitTracking", b =>
                {
                    b.HasOne("InvestIt.Data.Entities.BlockchainNetwork", "Network")
                        .WithMany("ApiRateLimitTrackings")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.MonitoredWallet", b =>
                {
                    b.HasOne("InvestIt.Data.Entities.BlockchainNetwork", "BlockchainNetwork")
                        .WithMany("MonitoredWallets")
                        .HasForeignKey("BlockchainNetworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BlockchainNetwork");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.MonitoringStatus", b =>
                {
                    b.HasOne("InvestIt.Data.Entities.BlockchainNetwork", "Network")
                        .WithMany("MonitoringStatuses")
                        .HasForeignKey("NetworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Network");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.NotificationQueue", b =>
                {
                    b.HasOne("InvestIt.Data.Entities.Transaction", "Transaction")
                        .WithMany("NotificationQueues")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.Transaction", b =>
                {
                    b.HasOne("InvestIt.Data.Entities.MonitoredWallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.BlockchainNetwork", b =>
                {
                    b.Navigation("ApiRateLimitTrackings");

                    b.Navigation("MonitoredWallets");

                    b.Navigation("MonitoringStatuses");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.MonitoredWallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("InvestIt.Data.Entities.Transaction", b =>
                {
                    b.Navigation("NotificationQueues");
                });
#pragma warning restore 612, 618
        }
    }
}
